language: python
python:
 - 2.7
 - 3.3
 - 3.4
 - 3.5
 - 3.6
env:
 - DATEUTIL_VERSION=2.1
 - DATEUTIL_VERSION=2.2
 - DATEUTIL_VERSION=2.3
 - DATEUTIL_VERSION=2.4.2
 - DATEUTIL_VERSION=2.5.2
 - DATEUTIL_VERSION=2.6.0
install:
 - pip install python-dateutil==$DATEUTIL_VERSION
 - python setup.py install
script: sh examples/update-slacklog-rss.sh
