language: python
python:
 - 2.6
 - 2.7
 - 3.4
env:
 - DATEUTIL_VERSION=2.2
install:
 - pip install python-dateutil==$DATEUTIL_VERSION
 - python setup.py install
script: sh examples/update-slacklog-rss.sh
